services:
  - type: web
    name: phonetique-fr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: PORT
        value: "10000"
      - key: WIKTIONARY_API_TIMEOUT
        value: "30"
      - key: MAX_CONTENT_LENGTH
        value: "16777216"  # 16MB en bytes
      - key: GUNICORN_WORKERS
        value: "4" 